language: node_js
node_js:
  - "0.10"
  - "4.3"

before_install:
  - sudo apt-get update
  - sudo apt-get install zookeeperd
  - npm -g install npm@latest-2

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

