language: node_js
node_js:
  - "0.10"
  - "4.2"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install zookeeperd"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

